version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"  # For Node.js debugging
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
      - FAST_REFRESH=true
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install && npm start"
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    command: npm run test:ci
    
  lint:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "echo 'Running ESLint...' && npx eslint --ext .js,.jsx,.ts,.tsx ./src --format stylish || echo 'Linting failed with errors'" 